site_name: 新火集
site_url: https://xinhuoji.netlify.app/
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  favicon: logo.png
  logo: logo.png
  font: false
nav:
  - 主页:
    - index.md
    - 与薪火集相比: prosncons.md
  - 鲜花: 
    - flower.md
    - 白日梦: 046985/1.md
plugins:
  - meta
  - tags
  - search:
      lang: zh
      jieba_dict: dict.txt
  - optimize:
      optimize: false
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - css/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css