site_name: 新火集
site_url: https://xinhuoji.netlify.app/
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - navigation.indexes
plugins:
  - blog:
      blog_dir: .
      post_readtime: false
      archive: false
  - tags
  - search:
      lang: zh
      jieba_dict: dict.txt.small
  - optimize:
      optimize: false
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_css:
extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js