site_name: 新火集
site_url: https://xinhuoji.netlify.app/
theme:
  name: material
  language: zh
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js